//
//  AuthorQuotes.swift
//  Evlla
//
//  Created by Dambar Bista on 3/30/23.
//  Copyright © 2023 Dambar Bista. All rights reserved.
//

import Foundation

struct MostPopular {
    var catagories: [QuotesCatagory] = [
        // MARK: - Sadhguru
        QuotesCatagory(name: "Sadhguru", image: "sadhguru", quotes: [
            "The only way to experience true wellbeing is to turn inward. This is what yoga means – not up, not out, but in.",
            "The sign of intelligence is that you are constantly wondering. Idiots are always dead sure about every damn thing they are doing in their life.",
            "How deeply you touch another life is how rich your life is.",
            "The past is memory. The future is imagination. And you are right here, right now.",
            "Don’t be dead serious about your life – it’s just a play.",
            "Love is not about getting what you want. It is an opportunity to lose yourself.” sadhguru quote on love",
            "Love is your quality. Love is not what you do. Love is what you are.",
            "If someone is nasty to you, first try love. If that does not work, compassion. If that does not work, distance.",
            "But to be loving is simply this: a willingness to respond freely and openly. Right now, it may be limited to one or two people in your lives. But it is possible to extend this ability to embrace the entire world.",
            "Love is not a joy; it is a deep wonderful pain. It is a very deep, tearing, wonderful pain. Something within you should tear; not just something, everything within you should tear. Only then you know what love is. If it feels pleasant, that’s not love; it’s just convenience. Maybe you felt a little affection. If you have ever loved, everything inside you tears apart, really tears apart. It’s painful but wonderful. That’s how it is.",
            "All the loving acts that two human beings are capable of, the simple act of holding hands can often become the most intimate.",
            "If you learn to laugh at your own stupidity, all the rubbish in you will turn into manure very fast. And manure is good for growth.",
            "If your sadness is reminding you that you are incomplete, it is good. Make use of your sadness to grow. When sadness sets in, if you become more compassionate, more caring, and more loving, you have some sense in you.",
            "Today, if you have one depressing thought in you, you will sit depressed. Why? The whole cosmos is going on phenomenally well today, but that does not matter. In your mind there is one thought – not too many, just one – that is bothering you, that will depress you and put you in the dumps.",
            "When you consciously rise above your likes and dislikes, that is maturity.",
            "Whether it is your work, your love, or your life – unless you throw your entire self into it, you will never really know it.",
            "If you learn to include others as a part of yourself, your life will become an expression of joyfulness, not a pursuit of happiness.",
            "Joy does not rain upon you – it blossoms from within. Whatever the situation, if you are joyful, life is a celebration.",
            "If you are forming relationships to seek happiness – you trying to squeeze happiness out of someone and that person trying to squeeze happiness out of you – this is going to be a painful relationship after some time.",
            "Whatever you wish to do, you must bring yourself to a moment of joy and clarity within yourself. Why I am saying joy is because when you are happy you are not compulsive. When you are very happy and clear, at that time if you look at things and see that ‘Yes, this is what is more sensible for me’ – just do that. It does not matter if it feels like hell; it does not matter if you go through hell for ten years, you just do that, because that is where your wellbeing is.",
            "It is possible to transform the greatest adversity into a stepping-stone for personal growth. If you take one hundred percent responsibility for the way you are now, a brighter tomorrow is a possibility.",
            "Finding joy within and giving joy to everyone around you is the foundation that is needed for ultimate well-being.",
            "Peace and joy are the basic requirements for a life of well-being.",
            "When pain, misery, or anger happen, it is time to look within you, not around you.",
            "When you are Joyful, you are not in conflict with anyone, and you do the most wonderful things.",
            "If you maintain exuberance of energy, freshness of mind, and a loving heart, every day will be a new adventure.",
            "Do not try to please anyone. If you are truly Joyful and an overflow of Humanity, everyone will be pleased with you.",
            "If you try to squeeze joy out of people, only pain will come.",
            "Loosen up a bit – laugh more, get involved with people around you, do simple things. If you only do very important things, you will become dead serious.",
            "If you resist change, you resist life.",
            "The most beautiful moments in life are moments when you are expressing your joy, not when you are seeking it.",
            "The quality of your life depends on how well you manage your body, your mind, your emotion, your situations, your home, your communities, nations, your life in general and the world.",
            "When you become conscious that Life is ticking away, you will make the best out of it.",
            "Too many people are hungry not because there is dearth of food. It is because there is dearth of love and care in human hearts.",
            "If you strive to make yourself in such a way that no one can help loving you, life will blossom into Beauty and Prosperity.",
            "With a heart full of devotion, meticulousness will come naturally.",
            "Without knowing the sweetness of love and the overwhelming nature of the Divine, you are yet to touch life.",
            "If you eliminate the need to get something out of relationships and naturally overflow with joy, you can have fabulous relationships with all sorts of people.",
            "Love is a longing to include someone as a part of yourself. It is a possibility to become more than what you are by inclusion.",
            "I understood that being loving and compassionate is not an idea. To live in empathy is not some esoteric principle. This is the way a human being is made. If you do not identify with anything you have accumulated over a period of time, including your body and mind, you will be able to experience this.",
            "For most people, love is initially a joy, but after a while it becomes an anxiety. Why? Because this key has legs and a will of its own. You can’t keep it in your pocket or hang it around your neck. When you try to do that, two lives are heading straight for disaster!",
            "A spouse is not a destination but a fellow traveler.",
            "Lovers and devotees must be allowed a certain margin. Otherwise, just hard logic will kill both love and devotion.",
            "Once you are blissful by your own nature, your life becomes an expression of your blissfulness, not a pursuit of happiness.",
            "I learned to create a little more space between my thoughts and actions — actually between my feelings and reactions. This is extremely important; without it, life can be a real roller coaster ride.",
            "Human folly is that people are always trying to extract joy from the outside. You may use the outside as a stimulus or trigger, but the real thing always comes from within."
        ]),
        
        // MARK: - Einstein
        QuotesCatagory(name: "Albert Einstein", image: "einstein",quotes: [
            "Imagination is more important than knowledge.",
            "The important thing is not to stop questioning. Curiosity has its own reason for existence.",
            "Try not to become a man of success, but rather try to become a man of value.",
            "Once we accept our limits, we go beyond them.",
            "Logic will get you from A to B. Imagination will take you everywhere.",
            "A person who never made a mistake never tried anything new.",
            "Education is not the learning of facts, but the training of the mind to think.",
            "The only source of knowledge is experience.",
            "Peace cannot be kept by force; it can only be achieved by understanding.",
            "The difference between genius and stupidity is that genius has its limits.",
            "If you can't explain it simply, you don't understand it well enough.",
            "The true sign of intelligence is not knowledge but imagination.",
            "No problem can be solved from the same level of consciousness that created it.",
            "Information is not knowledge.",
            "We cannot solve our problems with the same thinking we used when we created them.",
            "The important thing is not to stop questioning. Curiosity has its own reason for existence.",
            "I have no special talent. I am only passionately curious.",
            "In the middle of difficulty lies opportunity.",
            "The measure of intelligence is the ability to change.",
            "The most beautiful thing we can experience is the mysterious. It is the source of all true art and science.",
            "I never teach my pupils, I only attempt to provide the conditions in which they can learn.",
            "There are two ways to live: you can live as if nothing is a miracle; you can live as if everything is a miracle.",
            "Only a life lived for others is a life worthwhile.",
            "The important thing is not to stop questioning. Curiosity has its own reason for existence.",
            "We cannot solve our problems with the same thinking we used when we created them.",
            "We cannot despair of humanity, since we ourselves are human beings.",
            "Weakness of attitude becomes weakness of character.",
            "No problem can be solved from the same level of consciousness that created it.",
            "Everything should be made as simple as possible, but not simpler.",
            "Education is what remains after one has forgotten what one has learned in school.",
            "Reality is merely an illusion, albeit a very persistent one.",
            "In order to be an immaculate member of a flock of sheep, one must above all be a sheep oneself.",
            "The only way to escape the corruptible effect of praise is to go on working.",
            "God does not play dice with the universe.",
            "The whole of science is nothing more than a refinement of everyday thinking.",
            "Science without religion is lame, religion without science is blind.",
            "Most people say that it is the intellect which makes a great scientist. They are wrong: it is character.",
            "The hardest thing to understand in the world is the income tax.",
            "I want to know God's thoughts; the rest are details.",
            "It is the supreme art of the teacher to awaken joy in creative expression and knowledge.",
            "The most incomprehensible thing about the world is that it is comprehensible.",
            "I know not with what weapons World War III will be fought, but World War IV will be fought with sticks and stones.",
            "The release of atom power has changed everything except our way of thinking...the solution to this problem lies in the heart of mankind. If only I had known, I should have become"
        ]),
        
        // MARK: - Steve Jobs
        QuotesCatagory(name: "Steve Jobs", image: "steve", quotes: [
            "Why join the navy if you can be a pirate?",
            "Don’t let the noise of others’ opinions drown out your own inner voice.",
            "Design is not just what it looks like and feels like. Design is how it works",
            "You can’t just ask customers what they want and then try to give that to them. By the time you get it built, they’ll want something new.",
            "You've baked a really lovely cake, but then you've used dog shit for frosting.",
            "Simple can be harder than complex. You have to work hard to get your thinking clean to make it simple. But it’s worth it in the end because once you get there, you can move mountains.",
            "We don’t get a chance to do that many things, and everyone should be really excellent. Because this is our life.",
            "If you live each day as it was your last, someday you'll most certainly be right",
            "You can’t con people in this business. The products speak for themselves.",
            "The people who are crazy enough to think they can change the world are the ones who do.",
            "What a computer is to me is the most remarkable tool that we have ever come up with. It's the equivalent of a bicycle for our minds.",
            "Sometimes when you innovate, you make mistakes. It is best to admit them quickly, and get on with improving your other innovations.",
            "A leader leads by example, whether he intends to or not.",
            "I would trade all of my technology for an afternoon with Socrates.",
            "Remembering that I'll be dead soon is the most important tool I've ever encountered to help me make the big choices in life.",
            "Creativity is just connecting things.",
            "Don't be trapped by dogma – which is living with the results of other people's thinking.",
            "Be a yardstick of quality. Some people aren't used to an environment where excellence is expected.",
            "Have the courage to follow your heart and intuition. They somehow already know what you truly want to become. Everything else is secondary.",
            "Details matter, it's worth waiting to get it right.",
            "…love what you do. If you haven't found it yet, keep looking. Don't settle.",
            "If you really look closely, most overnight successes took a long time.",
            "Focusing is about saying No.",
            "I’m convinced that about half of what separates the successful entrepreneurs from the non-successful ones is pure perseverance.",
            "Things don't have to change the world to be important.",
            "Real artists ship.",
            "My model for business is The Beatles. They balanced each other and the total was greater than the sum of the parts. That’s how I see business: great things in business are never done by one person, they’re done by a team of people.",
            "If you don’t love something, you’re not going to go the extra mile, work the extra weekend, challenge the status quo as much.",
            "Your time is limited, so don't waste it living someone else's life.",
            "People who know what they’re talking about don’t need PowerPoint.",
            "People think focus means saying yes to the thing you’ve got to focus on. It means saying no to the hundred other good ideas that there are. You have to pick carefully.",
            "Let’s go invent tomorrow instead of worrying about what happened yesterday.",
            "Being the richest man in the cemetery doesn’t matter to me … Going to bed at night saying we’ve done something wonderful… that’s what matters to me.",
            "I'm as proud of what we don't do as I am of what we do.",
            "You’ve baked a really lovely cake, but then you’ve used dog shit for frosting.",
            "I think if you do something and it turns out pretty good, then you should go do something else wonderful, not dwell on it for too long. Just figure out what’s next.",
            "Quality is more important than quantity. One home run is much better than two doubles.",
            "That’s been one of my mantras – focus and simplicity. Simple can be harder than complex; you have to work hard to get your thinking clean to make it simple.",
            "If you are working on something exciting that you really care about, you don’t have to be pushed. The vision pulls you.",
            "We’re here to put a dent in the universe. Otherwise why else even be here?",
            "My job is to not be easy on people. My job is to make them better.",
            "The only way to do great work is to love what you do.",
            "I'm the only person I know that's lost a quarter of a billion dollars in one year.... It's very character-building.",
            "You have to trust in something, your gut, destiny life, karma, whatever this approach has never let me down.",
            "Older people sit down and ask: What is it? But the boy asks: What can I do with it?",
            "One way to remember who you are is to remember who your heroes are.",
            "We made the buttons on the screen look so good you'll want to lick them.",
            "I want to put a ding in the universe.",
            "Stay hungry. Stay foolish."
        ]),
        
        // MARK: - Oprah Winfrey
        QuotesCatagory(name: "Oprah Winfrey", image: "oprah", quotes: [
            "Turn your wounds into wisdom.",
            "The biggest adventure you can ever take is to live the life of your dreams.",
            "You become what you believe.",
            "You can have it all. Just not all at once.",
            "I believe that one of life's greatest risks is never daring to risk.",
            "The biggest challenge in life is being yourself… in a world trying to make you like everyone else.",
            "Think like a queen. A queen is not afraid to fail. Failure is another steppingstone to greatness.",
            "The more you praise and celebrate your life, the more there is in life to celebrate.",
            "Where there is no struggle, there is no strength.",
            "The greatest discovery of all time is that a person can change his future by merely changing his attitude.",
            "I don't believe in failure. It is not failure if you enjoyed the process.",
            "Create the highest, grandest vision possible for your life, because you become what you believe.",
            "Challenges are gifts that force us to search for a new center of gravity. Don't fight them. Just find a new way to stand.",
            "The only courage you ever need is the courage to live the life of your dreams.",
            "You are responsible for your life. You can't keep blaming somebody else for your dysfunction. Life is really about moving on.",
            "The key to realizing a dream is to focus not on success but significance, and then even the small steps and little victories along your path will take on greater meaning.",
            "You get in life what you have the courage to ask for.",
            "The biggest adventure you can ever take is to live the life of your dreams.",
            "I trust that everything happens for a reason, even when we're not wise enough to see it.",
            "I've come to believe that each of us has a personal calling that's as unique as a fingerprint - and that the best way to succeed is to discover what you love and then find a way to offer it to others in the form of service, working hard, and also allowing the energy of the universe to lead you.",
            "The more thankful I became, the more my bounty increased. That's because - for sure - what you focus on expands. When you focus on the goodness in life, you create more of it.",
            "Do the one thing you think you cannot do. Fail at it. Try again. Do better the second time. The only people who never tumble are those who never mount the high wire. This is your moment. Own it.",
            "The biggest adventure you can ever take is to live the life of your dreams.",
            "Where there is no struggle, there is no strength.",
            "If a man wants you, nothing can keep him away. If he doesn't want you, nothing can make him stay.",
            "The reason I've been able to be so financially successful is my focus has never, ever for one minute been money.",
            "The thing you fear most has no power. Your fear of it is what has the power. Facing the truth really will set you free.",
            "Be thankful for what you have; you'll end up having more. If you concentrate on what you don't have, you will never, ever have enough.",
            "If you don't know what your passion is, realize that one reason for your existence on earth is to find it.",
            "What I know is, is that if you do work that you love, and the work fulfills you, the rest will come.",
        ]),
        
        // MARK: - Abraham Lincoln
        QuotesCatagory(name: "Abraham Lincoln", image: "abraham", quotes: [
            "Whatever you are, be a good one.",
            "I am not bound to win, but I am bound to be true.",
            "Better to remain silent and be thought a fool than to speak out and remove all doubt.",
            "In the end, it's not the years in your life that count. It's the life in your years.",
            "Nearly all men can stand adversity, but if you want to test a man's character, give him power.",
            "I will prepare and someday my chance will come.",
            "I walk slowly, but I never walk backward.",
            "Things may come to those who wait, but only the things left by those who hustle.",
            "Give me six hours to chop down a tree and I will spend the first four sharpening the axe.",
            "Whatever you are, be a good one.",
            "You can fool some of the people all of the time, and all of the people some of the time, but you cannot fool all of the people all of the time.",
            "I'm a success today because I had a friend who believed in me and I didn't have the heart to let him down.",
            "The best way to predict your future is to create it.",
            "My great concern is not whether you have failed, but whether you are content with your failure.",
            "I have not failed. I've just found 10,000 ways that won't work.",
            "When I do good, I feel good. When I do bad, I feel bad. That's my religion.",
            "Most folks are as happy as they make up their minds to be.",
            "The best thing about the future is that it comes one day at a time.",
            "I'm a slow walker, but I never walk back.",
            "When you reach the end of your rope, tie a knot and hang on.",
            "The probability that we may fail in the struggle ought not to deter us from the support of a cause we believe to be just.",
            "A friend is one who has the same enemies as you have.",
            "You cannot escape the responsibility of tomorrow by evading it today.",
            "The things I want to know are in books; my best friend is the man who'll get me a book I ain't read.",
            "I am a slow walker, but I never walk back.",
            "The best thing about the future is that it comes one day at a time.",
            "I don't like that man. I must get to know him better.",
            "I don't know who my grandfather was; I am much more concerned to know what his grandson will be.",
            "I am not concerned that you have fallen; I am concerned that you arise.",
            "Tact is the ability to describe others as they see themselves.",
            "All that I am, or hope to be, I owe to my angel mother.",
            "I'm a success today because I had a friend who believed in me and I didn't have the heart to let him down.",
            "I have been driven many times upon my knees by the overwhelming conviction that I had nowhere else to go.",
            "Those who deny freedom to others deserve it not for themselves.",
            "Character is like a tree and reputation its shadow. The shadow is what we think it is and the tree is the real thing.",
            "With public sentiment, nothing can fail; without it, nothing can succeed.",
            "I never had a policy; I have just tried to do my very best each and every day.",
            "I would rather be a little nobody"
        ]),
        
        // MARK: - Maya Angelou
        QuotesCatagory(name: "Maya Angelou", image: "mayaAng", quotes: [
            "I've learned that people will forget what you said, people will forget what you did, but people will never forget how you made them feel.",
            "Try to be a rainbow in someone's cloud.",
            "If you don't like something, change it. If you can't change it, change your attitude.",
            "Success is liking yourself, liking what you do, and liking how you do it.",
            "I've learned that making a living is not the same thing as making a life.",
            "We may encounter many defeats but we must not be defeated.",
            "I can be changed by what happens to me. But I refuse to be reduced by it.",
            "Nothing will work unless you do.",
            "If you have only one smile in you give it to the people you love.",
            "Courage is the most important of all the virtues because without courage, you can't practice any other virtue consistently.",
            "My mission in life is not merely to survive, but to thrive; and to do so with some passion, some compassion, some humor, and some style.",
            "You may not control all the events that happen to you, but you can decide not to be reduced by them.",
            "I've learned that whenever I decide something with an open heart, I usually make the right decision.",
            "I've learned that even when I have pains, I don't have to be one.",
            "I've learned that every day you should reach out and touch someone. People love a warm hug, or just a friendly pat on the back.",
            "We need much less than we think we need.",
            "I've learned that you shouldn't go through life with a catcher's mitt on both hands; you need to be able to throw something back.",
            "I love to see a young girl go out and grab the world by the lapels. Life's a bitch. You've got to go out and kick ass.",
            "I did then what I knew how to do. Now that I know better, I do better.",
            "I've learned that you can tell a lot about a person by the way (s)he handles these three things: a rainy day, lost luggage, and tangled Christmas tree lights.",
            "We can learn to see each other and see ourselves in each other and recognize that human beings are more alike than we are unalike.",
            "The desire to reach for the stars is ambitious. The desire to reach hearts is wise.",
            "You may encounter many defeats, but you must not be defeated. In fact, it may be necessary to encounter the defeats, so you can know who you are, what you can rise from, how you can still come out of it.",
            "The quality of strength lined with tenderness is an unbeatable combination.",
            "A wise woman wishes to be no one's enemy; a wise woman refuses to be anyone's victim.",
            "It's one of the greatest gifts you can give yourself, to forgive. Forgive everybody.",
            "I've learned that people will do anything for a person who will make them feel loved.",
            "We delight in the beauty of the butterfly, but rarely admit the changes it has gone through to achieve that beauty.",
            "Life is not measured by the number of breaths you take but by the moments that take your breath away.",
            "I know why the caged bird sings.",
            "The greatest gift you can give yourself is to forgive yourself.",
            "Love is like a virus. It can happen to anybody at any time.",
        ]),
        
        // MARK: - Mahatma Gandhi
        QuotesCatagory(name: "Mahatma Gandhi", image: "matmaGandi", quotes: [
            "The weak can never forgive. Forgiveness is the attribute of the strong.",
            "Be the change you want to see in the world.",
            "An eye for an eye will only make the whole world blind.",
            "The best way to find yourself is to lose yourself in the service of others.",
            "You must be the change you wish to see in the world.",
            "Happiness is when what you think, what you say, and what you do are in harmony.",
            "The difference between what we do and what we are capable of doing would suffice to solve most of the world's problems.",
            "Live as if you were to die tomorrow. Learn as if you were to live forever.",
            "Strength does not come from physical capacity. It comes from an indomitable will.",
            "Freedom is not worth having if it does not include the freedom to make mistakes.",
            "The greatness of a nation can be judged by the way its animals are treated.",
            "An ounce of practice is worth more than tons of preaching.",
            "First they ignore you, then they laugh at you, then they fight you, then you win.",
            "The future depends on what you do today.",
            "The best way to find yourself is to lose yourself in service to others.",
            "You can't change how people treat you or what they say about you. All you can do is change how you react to it.",
            "The difference between what we do and what we are capable of doing would suffice to solve most of the world's problems.",
            "There is more to life than increasing its speed.",
            "You may never know what results come of your actions, but if you do nothing, there will be no results.",
            "A man is but the product of his thoughts. What he thinks, he becomes.",
            "The enemy is fear. We think it is hate; but, it is fear.",
            "The weak can never forgive. Forgiveness is the attribute of the strong.",
            "Strength does not come from winning. Your struggles develop your strengths. When you go through hardships and decide not to surrender, that is strength.",
            "In a gentle way, you can shake the world.",
            "Freedom is not worth having if it does not include the freedom to make mistakes.",
            "The best way to find yourself is to lose yourself in the service of others.",
            "The greatness of a nation and its moral progress can be judged by the way its animals are treated.",
            "Happiness is when what you think, what you say, and what you do are in harmony.",
            "The difference between what we do and what we are capable of doing would suffice to solve most of the world's problems.",
            "The true measure of any society can be found in how it treats its most vulnerable members.",
            "The weak can never forgive. Forgiveness is the attribute of the strong.",
            "In doing something, do it with love or never do it at all.",
            "It is health that is the real wealth and not pieces of gold and silver.",
            "If you want to change the world, change yourself.",
            "The best way to find yourself is to lose yourself in the service of others.",
            "Live simply so that others may simply live.",
            "Anger and intolerance are the enemies of correct understanding.",
            "Satisfaction lies in the effort, not in the attainment. Full effort is full victory.",
            "Be the change that you wish to see in the world.",
        ]),
        
        // MARK: - Martin Luther King Jr
        QuotesCatagory(name: "MLK Jr", image: "martinLuther", quotes: [
            "The time is always right to do what is right.",
            "Injustice anywhere is a threat to justice everywhere.",
            "I have a dream that one day this nation will rise up and live out the true meaning of its creed: We hold these truths to be self-evident, that all men are created equal.",
            "Darkness cannot drive out darkness; only light can do that. Hate cannot drive out hate; only love can do that.",
            "Our lives begin to end the day we become silent about things that matter.",
            "Faith is taking the first step even when you can't see the whole staircase.",
            "The ultimate measure of a man is not where he stands in moments of comfort and convenience, but where he stands at times of challenge and controversy.",
            "The function of education is to teach one to think intensively and to think critically. Intelligence plus character - that is the goal of true education.",
            "I have decided to stick with love. Hate is too great a burden to bear.",
            "Love is the only force capable of transforming an enemy into a friend.",
            "A genuine leader is not a searcher for consensus but a molder of consensus.",
            "The quality, not the longevity, of one's life is what is important.",
            "Our scientific power has outrun our spiritual power. We have guided missiles and misguided men.",
            "I believe that unarmed truth and unconditional love will have the final word in reality. This is why right, temporarily defeated, is stronger than evil triumphant.",
            "The ultimate tragedy is not the oppression and cruelty by the bad people but the silence over that by the good people.",
            "We must learn to live together as brothers or perish together as fools.",
            "We may have all come on different ships, but we're in the same boat now.",
            "Life's most persistent and urgent question is, 'What are you doing for others?'",
            "I look to a day when people will not be judged by the color of their skin, but by the content of their character.",
            "Freedom is never voluntarily given by the oppressor; it must be demanded by the oppressed.",
            "We must accept finite disappointment, but never lose infinite hope.",
            "True peace is not merely the absence of tension; it is the presence of justice.",
            "We must build dikes of courage to hold back the flood of fear.",
            "If you can't fly then run, if you can't run then walk, if you can't walk then crawl, but whatever you do you have to keep moving forward.",
            "The time is always right to do what is right.",
            "We must develop and maintain the capacity to forgive. He who is devoid of the power to forgive is devoid of the power to love.",
            "If you want to change the world, pick up your pen and write.",
            "The function of leadership is to produce more leaders, not more followers.",
            "We must use time creatively, in the knowledge that the time is always ripe to do right.",
            "The true neighbor will risk his position, his prestige and even his life for the welfare of others.",
            "We are not makers of history. We are made by history.",
            "The ultimate measure of a man is not where he stands in moments of comfort and convenience, but where he stands at times of challenge and controversy.",
            "There comes a time when one must take a position that is neither safe, nor politic",
        ]),
        
        // MARK: - Helen Keller
        QuotesCatagory(name: "Helen Keller", image: "helenKeller", quotes: [
            "The best and most beautiful things in the world cannot be seen or even touched - they must be felt with the heart.",
            "Alone we can do so little; together we can do so much.",
            "The only thing worse than being blind is having sight but no vision.",
            "Life is a succession of lessons which must be lived to be understood.",
            "Keep your face to the sunshine and you cannot see a shadow.",
            "The most pathetic person in the world is someone who has sight, but has no vision.",
            "No pessimist ever discovered the secrets of the stars, or sailed to an uncharted land, or opened a new heaven to the human spirit.",
            "It is a terrible thing to see and have no vision.",
            "Security is mostly a superstition. Life is either a daring adventure or nothing.",
            "The highest result of education is tolerance.",
            "What we once enjoyed and deeply loved we can never lose, for all that we love deeply becomes a part of us.",
            "We could never learn to be brave and patient if there were only joy in the world.",
            "We may have found a cure for most evils; but we have found no remedy for the worst of them all, the apathy of human beings.",
            "I am only one, but still I am one. I cannot do everything, but still I can do something; and because I cannot do everything, I will not refuse to do something that I can do.",
            "The best way out is always through.",
            "Character cannot be developed in ease and quiet. Only through experience of trial and suffering can the soul be strengthened, vision cleared, ambition inspired, and success achieved.",
            "The only true disability is the inability to accept and celebrate diversity.",
            "Happiness is not attained through self-gratification, but through fidelity to a worthy purpose.",
            "I seldom think about my limitations, and they never make me sad. Perhaps there is just a touch of yearning at times; but it is vague, like a breeze among flowers.",
            "Although the world is full of suffering, it is also full of the overcoming of it.",
            "The marvelous richness of human experience would lose something of rewarding joy if there were no limitations to overcome.",
            "When we do the best we can, we never know what miracle is wrought in our life or the life of another.",
            "The only way to have a friend is to be one.",
            "True happiness is not attained through self-gratification, but through fidelity to a worthy purpose.",
            "Many people know so little about what is beyond their short range of experience. They look within themselves - and find nothing! Therefore they conclude that there is nothing outside themselves either.",
            "I long to accomplish a great and noble task, but it is my chief duty to accomplish small tasks as if they were great and noble.",
            "The best preparation for good work tomorrow is to do good work today.",
            "The most important day of my life, I remember, went like this: It was a beautiful day in March, 1887. I was a little baby girl, sitting on my mother's lap in the warm sunshine of Alabama. The house was all a-tremble with preparations for something which was to happen the next day.",
            "Self-pity is our worst enemy and if we yield to it, we can never do anything good in the world.",
            "The welfare of each is bound up in the welfare of all.",
            "Faith is the strength by which a shattered world shall emerge into the light.",
        ]),
        
        // MARK: - Mark Twain
        QuotesCatagory(name: "Mark Twain", image: "markTwain", quotes: [
            "The secret of getting ahead is getting started.",
            "Age is an issue of mind over matter. If you don't mind, it doesn't matter.",
            "If you tell the truth, you don't have to remember anything.",
            "Good friends, good books, and a sleepy conscience: this is the ideal life.",
            "Never put off till tomorrow what you can do the day after tomorrow.",
            "Whenever you find yourself on the side of the majority, it is time to pause and reflect.",
            "The man who does not read good books has no advantage over the man who cannot read them.",
            "It's not the size of the dog in the fight, it's the size of the fight in the dog.",
            "Kindness is the language which the deaf can hear and the blind can see.",
            "To succeed in life, you need two things: ignorance and confidence.",
            "The difference between the almost right word and the right word is really a large matter—'tis the difference between the lightning bug and the lightning.",
            "A person who won't read has no advantage over one who can't read.",
            "I have never let my schooling interfere with my education.",
            "Wrinkles should merely indicate where smiles have been.",
            "If you don't read the newspaper, you're uninformed. If you read the newspaper, you're mis-informed.",
            "I didn't attend the funeral, but I sent a nice letter saying I approved of it.",
            "There are basically two types of people. People who accomplish things, and people who claim to have accomplished things. The first group is less crowded.",
            "Don't go around saying the world owes you a living. The world owes you nothing. It was here first.",
            "The fear of death follows from the fear of life. A man who lives fully is prepared to die at any time.",
            "If you don't like the weather in New England, just wait a few minutes.",
            "If you could kick the person in the pants responsible for most of your trouble, you wouldn't sit for a month.",
            "The best way to cheer yourself is to try to cheer someone else up.",
            "If you don't know where you're going, any road will take you there.",
            "The man who doesn't read good books has no advantage over the man who can't read them.",
            "In the beginning of a change, the patriot is a scarce man, and brave, and hated and scorned. When his cause succeeds, the timid join him, for then it costs nothing to be a patriot.",
            "There are lies, damned lies and statistics.",
            "All you need in this life is ignorance and confidence; then success is sure.",
            "Golf is a good walk spoiled.",
            "It is better to keep your mouth closed and let people think you are a fool than to open it and remove all doubt.",
            "The more things are forbidden, the more popular they become.",
            "The reports of my death have been greatly exaggerated.",
            "The only way to keep your health is to eat what you don't want, drink what you don't like, and do what you'd rather not.",
            "The secret of life is to appreciate the pleasure of being terribly, terribly deceived.",
            "Work and play are words used to describe the same thing under differing conditions.",
            "I didn't have time to write a short letter, so I wrote a long one instead.",
        ])
    ]
}
