//
//  PopularQuotesDataModel.swift
//  Evlla
//
//  Created by Dambar Bista on 4/12/20.
//  Copyright © 2020 Dambar Bista. All rights reserved.
//

import Foundation

// this method is to store popular quotes.
// first i created struct of popularDataModel then impleting here on array.

struct PopularQuotesModel {
    
    static let quotesList = [

        PopularQuotesData(quotes: "If you aren’t big enough to stand criticism, you’re too small to be praised. - Earl Deason"),
        PopularQuotesData(quotes: "I measure the strength of a spirit by how much truth it can take. - Friedrich Nietzsche"),
        PopularQuotesData(quotes: "Never give up on what you really want to do. The person with big dreams is more powerful than one with all the facts. - Albert Einstein"),
        PopularQuotesData(quotes: "The greatest glory in living lies not in never falling, but in rising every time we fall. - Nelson Mandela"),
        PopularQuotesData(quotes: "The way to get started is to quit talking and begin doing. - Walt Disney"),
        PopularQuotesData(quotes: "Your time is limited, so don't waste it living someone else's life. Don't be trapped by dogma – which is living with the results of other people's thinking. - Steve Jobs"),
        PopularQuotesData(quotes: "If life were predictable it would cease to be life, and be without flavor. - Eleanor Roosevelt"),
        PopularQuotesData(quotes: "If you look at what you have in life, you'll always have more. If you look at what you don't have in life, you'll never have enough. - Oprah Winfrey"),
        
        PopularQuotesData(quotes: "If you set your goals ridiculously high and it's a failure, you will fail above everyone else's success. - James Cameron"
),
        PopularQuotesData(quotes: "Life is what happens when you're busy making other plans. - John Lennon"),
        PopularQuotesData(quotes: "Spread love everywhere you go. Let no one ever come to you without leaving happier. - Mother Teresa"),
        PopularQuotesData(quotes: "When you reach the end of your rope, tie a knot in it and hang on. - Franklin D. Roosevelt"),
        PopularQuotesData(quotes: "Always remember that you are absolutely unique. Just like everyone else. - Margaret Mead"),
        PopularQuotesData(quotes: "Don't judge each day by the harvest you reap but by the seeds that you plant. - Robert Louis Stevenson"),
        PopularQuotesData(quotes: "The future belongs to those who believe in the beauty of their dreams. - Eleanor Roosevel"),
        PopularQuotesData(quotes: "Tell me and I forget. Teach me and I remember. Involve me and I learn. - Benjamin Franklin"),
        PopularQuotesData(quotes: "The best and most beautiful things in the world cannot be seen or even touched - they must be felt with the heart. - Helen Keller"),
        PopularQuotesData(quotes: "It is during our darkest moments that we must focus to see the light. - Aristotle"),
        PopularQuotesData(quotes: "Whoever is happy will make others happy too. - Anne Frank"),
        PopularQuotesData(quotes: "Do not go where the path may lead, go instead where there is no path and leave a trail. - Ralph Waldo Emerson"),
        PopularQuotesData(quotes: "Twenty years from now you will be more disappointed by the things that you didn't do than by the ones you did do. So, throw off the bowlines, sail away from safe harbor, catch the trade winds in your sails. Explore, Dream, Discover. - Unknown"),
        PopularQuotesData(quotes: "First, have a definite, clear practical ideal; a goal, an objective. Second, have the necessary means to achieve your ends; wisdom, money, materials, and methods. Third, adjust all your means to that end. - Aristotle" ),
        PopularQuotesData(quotes: "Whatever the mind of man can conceive and believe, it can achieve. - Napoleon Hill"),
        PopularQuotesData(quotes:  "Dreaming, after all, is a form of planning. - Gloria Steinem"),
        PopularQuotesData(quotes: "If you look at what you have in life, you'll always have more. If you look at what you don't have in life, you'll never have enough. - Oprah Winfrey"),
        PopularQuotesData(quotes:  "I would rather die of passion than of boredom. - Vincent van Gogh"),
        PopularQuotesData(quotes: "I attribute my success to this: I never gave or took any excuse. - Florence Nightingale"),
        PopularQuotesData(quotes:  "If you're offered a seat on a rocket ship, don't ask what seat! Just get on. - Sheryl Sandberg"),
        PopularQuotesData(quotes: "I didn't fail the test. I just found 100 ways to do it wrong. - Benjamin Franklin"),
        PopularQuotesData(quotes: "I have learned over the years that when one's mind is made up, this diminishes fear. - Rosa Parks"),
        PopularQuotesData(quotes: "Too many of us are not living our dreams because we are living our fears. - Les Brown"),
        PopularQuotesData(quotes: "When everything seems to be going against you, remember that the airplane takes off against the wind, not with it. - Henry Ford"),
        PopularQuotesData(quotes:  "It does not matter how slowly you go as long as you do not stop. - Confucius"),
        PopularQuotesData(quotes: "Nothing is impossible, the word itself says, ‘I'm possible!'. - Audrey Hepburn"),
        PopularQuotesData(quotes:  "Life is 10% what happens to me and 90% of how I react to it. - Charles Swindoll"),
        PopularQuotesData(quotes: "You may be disappointed if you fail, but you are doomed if you don't try. - Beverly Sills"),
        PopularQuotesData(quotes: "Dream big and dare to fail. - Norman Vaughan"),
        PopularQuotesData(quotes: "Everything you've ever wanted is on the other side of fear. - George Addair"),
        PopularQuotesData(quotes: "An unexamined life is not worth living. - Socrates"),
        PopularQuotesData(quotes: "How wonderful it is that nobody need wait a single moment before starting to improve the world. - Anne Frank"),
        PopularQuotesData(quotes: "The most difficult thing is the decision to act, the rest is merely tenacity. - Amelia Earhart"),
        PopularQuotesData(quotes: "You become what you believe. - Oprah Winfrey"),
        PopularQuotesData(quotes:  "I alone cannot change the world, but I can cast a stone across the water to create many ripples. - Mother Teresa"),
        PopularQuotesData(quotes: "You miss 100% of the shots you don't take. - Wayne Gretzky"),
        PopularQuotesData(quotes: "Whether you think you can or you think you can't, you're right. - Henry Ford"),
        PopularQuotesData(quotes: "Winning isn't everything, but wanting to win is. - Vince Lombardi"),
        PopularQuotesData(quotes: "The question isn't who is going to let me; it's who is going to stop me. -Ayn Rand"),
        PopularQuotesData(quotes:  "I've learned that people will forget what you said, people will forget what you did, but people will never forget how you made them feel. - Maya Angelou"),
        PopularQuotesData(quotes: "The only person you are destined to become is the person you decide to be. - Ralph Waldo Emerson"),
        PopularQuotesData(quotes: "Believe you can and you're halfway there. - Theodore Roosevelt"),
        PopularQuotesData(quotes:  "People who succeed have momentum. The more they succeed, the more they want to succeed and the more they find a way to succeed. Similarly, when someone is failing, the tendency is to get on a downward spiral that can even become a self-fulfilling prophecy. - Tony Robbins"),
        PopularQuotesData(quotes:  "Before anything else, preparation is the key to success. - Alexander Graham Bell"),
        PopularQuotesData(quotes: "If you are not willing to risk the usual, you will have to settle for the ordinary. - Jim Rohn"),
        PopularQuotesData(quotes: "The only place where success comes before work is in the dictionary. - Vidal Sassoon"),
        PopularQuotesData(quotes: "If you genuinely want something, don't wait for it -- teach yourself to be impatient. - Gurbaksh Chahal"),
        PopularQuotesData(quotes: "If you want to achieve excellence, you can get there today. As of this second, quit doing less-than-excellent work. - Thomas J. Watson"),
        PopularQuotesData(quotes:  "You know you are on the road to success if you would do your job and not be paid for it. - Oprah Winfrey"),
        PopularQuotesData(quotes:  "Success is walking from failure to failure with no loss of enthusiasm. - Winston Churchill"),
        PopularQuotesData(quotes: "Always bear in mind that your own resolution to success is more important than any other one thing. - Abraham Lincoln"),
        PopularQuotesData(quotes: "Don't be afraid to give up the good to go for the great. - John D. Rockefeller"),
        PopularQuotesData(quotes: "Try not to become a man of success. Rather become a man of value. - Albert Einstein"),
        PopularQuotesData(quotes:  "Things work out best for those who make the best of how things work out. - John Wooden"),
        PopularQuotesData(quotes: "A successful man is one who can lay a firm foundation with the bricks others have thrown at him. - David Brinkley"),
        PopularQuotesData(quotes: "If you really look closely, most overnight successes took a long time. - Steve Jobs"),
        PopularQuotesData(quotes: "I failed my way to success. - Thomas Edison"),
        PopularQuotesData(quotes: "The road to success and the road to failure are almost exactly the same. - Colin R. Davis"),
        PopularQuotesData(quotes:  "Successful people do what unsuccessful people are not willing to do. Don't wish it were easier; wish you were better. - Jim Rohn"),
        PopularQuotesData(quotes: "It is better to fail in originality than to succeed in imitation. - Herman Melville"),
        PopularQuotesData(quotes: "The only limit to our realization of tomorrow will be our doubts of today. - Franklin D. Roosevelt"),
        PopularQuotesData(quotes: "The real test is not whether you avoid this failure, because you won't. It's whether you let it harden or shame you into inaction, or whether you learn from it; whether you choose to persevere. - Barack Obama"),
        PopularQuotesData(quotes: "There are no secrets to success. It is the result of preparation, hard work, and learning from failure. - Colin Powell"),
        PopularQuotesData(quotes: "Success seems to be connected with action. Successful people keep moving. They make mistakes but they don't quit. - Conrad Hilton"),
        PopularQuotesData(quotes: "I never dreamed about success, I worked for it. - Estee Lauder"),
        PopularQuotesData(quotes: "Success usually comes to those who are too busy to be looking for it. - Henry David Thoreau"),
        PopularQuotesData(quotes: "Don't be distracted by criticism. Remember -- the only taste of success some people get is to take a bite out of you. - Zig Ziglar"),
        PopularQuotesData(quotes: "Success is not final; failure is not fatal: It is the courage to continue that counts. - Winston S. Churchill"),
        PopularQuotesData(quotes: "I find that the harder I work, the more luck I seem to have. - Thomas Jefferson"),
        PopularQuotesData(quotes:  "The secret of success is to do the common thing uncommonly well. - John D. Rockefeller Jr."),
        PopularQuotesData(quotes: "Many of life's failures are people who did not realize how close they were to success when they gave up. - Thomas A. Edison"),
        PopularQuotesData(quotes: "Life is trying things to see if they work. - Ray Bradbury"),
        PopularQuotesData(quotes: "Your time is limited, so don't waste it living someone else's life. Don't be trapped by dogma -- which is living with the results of other people's thinking. - Steve Jobs"),
        PopularQuotesData(quotes: "Life is made of ever so many partings welded together. - Charles Dickens"),
        PopularQuotesData(quotes: "You have brains in your head. You have feet in your shoes. You can steer yourself any direction you choose. - Dr. Seuss"),
        PopularQuotesData(quotes:  "Life is either a daring adventure or nothing at all. - Helen Keller"),
        PopularQuotesData(quotes: "Love the life you live. Live the life you love. - Bob Marley"),
        PopularQuotesData(quotes: "In three words I can sum up everything I've learned about life: it goes on. - Robert Frost"),
        PopularQuotesData(quotes: "Life is a long lesson in humility. - James M. Barrie"),
        PopularQuotesData(quotes: "Keep smiling, because life is a beautiful thing and there's so much to smile about. - Marilyn Monroe"),
        PopularQuotesData(quotes: "Life is ours to be spent, not to be saved. - D. H. Lawrence"),
        PopularQuotesData(quotes: "Do not let making a living prevent you from making a life. - John Wooden"),
        PopularQuotesData(quotes:  "Life itself is the most wonderful fairy tale. - Hans Christian Andersen"),
        PopularQuotesData(quotes: "May you live all the days of your life. - Jonathan Swift"),
        PopularQuotesData(quotes: "Life is really simple, but we insist on making it complicated. - Confucius"),
        PopularQuotesData(quotes: "Go confidently in the direction of your dreams! Live the life you've imagined. - Henry David Thoreau"),
        PopularQuotesData(quotes:  "Live in the sunshine, swim the sea, drink the wild air. - Ralph Waldo Emerson"),
        PopularQuotesData(quotes: "You only live once, but if you do it right, once is enough. - Mae West"),
        PopularQuotesData(quotes: "The purpose of our lives is to be happy. - Dalai Lama"),
        PopularQuotesData(quotes: "Only a life lived for others is a life worthwhile. - Albert Einstein"),
        PopularQuotesData(quotes: "In this life we cannot do great things. We can only do small things with great love. - Mother Teresa"),
        PopularQuotesData(quotes: "The only impossible journey is the one you never begin. - Tony Robbins"),
        PopularQuotesData(quotes: "Life is never fair, and perhaps it is a good thing for most of us that it is not. - Oscar Wilde"),
        PopularQuotesData(quotes: "Never let the fear of striking out keep you from playing the game. - Babe Ruth"),
        PopularQuotesData(quotes: "Life is a succession of lessons which must be lived to be understood. - Ralph Waldo Emerson"),
        PopularQuotesData(quotes: "In the end, it's not the years in your life that count. It's the life in your years. - Abraham Lincoln"),
        PopularQuotesData(quotes: "You will face many defeats in life, but never let yourself be defeated. - Maya Angelou"),
        PopularQuotesData(quotes: "If life were predictable it would cease to be life and be without flavor. - Eleanor Roosevelt"),
        PopularQuotesData(quotes: "If you tell the truth, you don't have to remember anything. - Mark Twain"),
        PopularQuotesData(quotes: "I'm selfish, impatient and a little insecure. I make mistakes, I am out of control and at times hard to handle. But if you can't handle me at my worst, then you sure as hell don't deserve me at my best. ― Marilyn Monroe"),
        PopularQuotesData(quotes: "Be yourself; everyone else is already taken. ― Oscar Wilde"),
        PopularQuotesData(quotes:"Two things are infinite: the universe and human stupidity; and I'm not sure about the universe. ― Albert Einstein"),
        PopularQuotesData(quotes: "So many books, so little time. ― Frank Zappa"),
        PopularQuotesData(quotes: "Be who you are and say what you feel, because those who mind don't matter, and those who matter don't mind. ― Bernard M. Baruch"),
        PopularQuotesData(quotes: "A room without books is like a body without a soul. ― Marcus Tullius Cicero"),
        PopularQuotesData(quotes: "You've gotta dance like there's nobody watching,Love like you'll never be hurt,Sing like there's nobody listening,And live like it's heaven on earth. ― William W. Purkey"),
        PopularQuotesData(quotes: "You know you're in love when you can't fall asleep because reality is finally better than your dreams. ― Dr. Seuss"),
        PopularQuotesData(quotes:"Be the change that you wish to see in the world. ― Mahatma Gandhi"),
        PopularQuotesData(quotes: "In three words I can sum up everything I've learned about life: it goes on. ― Robert Frost"),
        PopularQuotesData(quotes: "If you want to know what a man's like, take a good look at how he treats his inferiors, not his equals. ― J.K. Rowling"),
        PopularQuotesData(quotes: "Don’t walk in front of me… I may not follow Don’t walk behind me… I may not lead Walk beside me… just be my friend ― Albert Camus"),
        PopularQuotesData(quotes: "No one can make you feel inferior without your consent. ― Eleanor Roosevel"),
        PopularQuotesData(quotes: "Friendship ... is born at the moment when one man says to another 'What! You too? I thought that no one but myself . . . ― C.S. Lewis"),
        PopularQuotesData(quotes: "A friend is someone who knows all about you and still loves you. ― Elbert Hubbard"),
        PopularQuotesData(quotes: "Always forgive your enemies; nothing annoys them so much. ― Oscar Wilde"),
        PopularQuotesData(quotes: "Live as if you were to die tomorrow. Learn as if you were to live forever. ― Mahatma Gandhi"),
        PopularQuotesData(quotes: "Darkness cannot drive out darkness: only light can do that. Hate cannot drive out hate: only love can do that. ― Martin Luther King Jr."),
        PopularQuotesData(quotes: "Without music, life would be a mistake. ― Friedrich Nietzsche"),
        PopularQuotesData(quotes: "We accept the love we think we deserve. ― Stephen Chbosky"),
        PopularQuotesData(quotes: "To be yourself in a world that is constantly trying to make you something else is the greatest accomplishment. ― Ralph Waldo Emerson"),
        PopularQuotesData(quotes: "I am so clever that sometimes I don't understand a single word of what I am saying. ― Oscar Wilde"),
        PopularQuotesData(quotes: "Here's to the crazy ones. The misfits. The rebels. The troublemakers. The round pegs in the square holes. The ones who see things differently. They're not fond of rules. And they have no respect for the status quo. You can quote them, disagree with them, glorify or vilify them. About the only thing you can't do is ignore them. Because they change things. They push the human race forward. And while some may see them as the crazy ones, we see genius. Because the people who are crazy enough to think they can change the world, are the ones who do. ― Rob Siltanen"),
        PopularQuotesData(quotes: "Insanity is doing the same thing, over and over again, but expecting different results. ― Narcotics Anonymous"),
        PopularQuotesData(quotes: "I believe that everything happens for a reason. People change so that you can learn to let go, things go wrong so that you appreciate them when they're right, you believe lies so you eventually learn to trust no one but yourself, and sometimes good things fall apart so better things can fall together. ― Marilyn Monroe"),
        PopularQuotesData(quotes: "To live is the rarest thing in the world. Most people exist, that is all. ― Oscar Wilde"),
        PopularQuotesData(quotes: "Have you ever been in love? Horrible isn't it? It makes you so vulnerable. It opens your chest and it opens up your heart and it means that someone can get inside you and mess you up. ― Neil Gaiman"),
        PopularQuotesData(quotes: "A day without sunshine is like, you know, night. ― Steve Martin"),
        PopularQuotesData(quotes: "Never put off till tomorrow what may be done day after tomorrow just as well. ― Mark Twain"),
        PopularQuotesData(quotes: "A reader lives a thousand lives before he dies, said Jojen. The man who never reads lives only one. ― George R.R. Martin"),
        PopularQuotesData(quotes: "That which does not kill us makes us stronger.― Friedrich Nietzsche"),
        PopularQuotesData(quotes: "Being deeply loved by someone gives you strength, while loving someone deeply gives you courage. ― Lao Tzu"),
        PopularQuotesData(quotes: "For every minute you are angry you lose sixty seconds of happiness. ― Ralph Waldo Emerson"),
        PopularQuotesData(quotes: "It is never too late to be what you might have been. ― George Eliot"),
        PopularQuotesData(quotes: "It takes a great deal of bravery to stand up to our enemies, but just as much to stand up to our friends. ― J.K. Rowling"),
        PopularQuotesData(quotes: "I love deadlines. I love the whooshing noise they make as they go by. ― Douglas Adams"),
        PopularQuotesData(quotes: "There is never a time or place for true love. It happens accidentally, in a heartbeat, in a single flashing, throbbing moment. ― Sarah Dessen"),
        PopularQuotesData(quotes: "My thoughts are stars I cannot fathom into constellations. ― John Green"),
        PopularQuotesData(quotes: "If you can't explain it to a six year old, you don't understand it yourself. ― Albert Einstein"),
        PopularQuotesData(quotes: "Love is that condition in which the happiness of another person is essential to your own. ― Robert A. Heinlein"),
        PopularQuotesData(quotes: "I'm not upset that you lied to me, I'm upset that from now on I can't believe you. ― Friedrich Nietzsche"),
        PopularQuotesData(quotes: "There is no greater agony than bearing an untold story inside you. ― Maya Angelou"),
        PopularQuotesData(quotes: "Anyone who thinks sitting in church can make you a Christian must also think that sitting in a garage can make you a car. ― Garrison Keillor"),
        PopularQuotesData(quotes: "I have always imagined that Paradise will be a kind of library. ― Jorge Luis Borges"),
        PopularQuotesData(quotes: "Everything you can imagine is real. ― Pablo Picasso"),
        PopularQuotesData(quotes: "Women and cats will do as they please, and men and dogs should relax and get used to the idea. ― Robert A. Heinlein"),
        PopularQuotesData(quotes: "If you only read the books that everyone else is reading, you can only think what everyone else is thinking. ― Haruki Murakami"),
        PopularQuotesData(quotes: "We don't see things as they are, we see them as we are. ― Anaïs Nin"),
        PopularQuotesData(quotes: "Sometimes the questions are complicated and the answers are simple.― Dr. Seuss"),
        PopularQuotesData(quotes: "We read to know we're not alone. ― William Nicholson"),
        PopularQuotesData(quotes: "You love me. Real or not real? I tell him, 'Real. ― Suzanne Collins"),
        PopularQuotesData(quotes: "Never trust anyone who has not brought a book with them. ― Lemony Snicket"),
        PopularQuotesData(quotes: "All you need is love. But a little chocolate now and then doesn't hurt. ― Charles M. Schulz"),
        PopularQuotesData(quotes: "Beauty is in the eye of the beholder and it may be necessary from time to time to give a stupid or misinformed beholder a black eye. ― Jim Henson"),
        PopularQuotesData(quotes: "Of course it is happening inside your head, Harry, but why on earth should that mean that it is not real? ― J.K. Rowling"),
        PopularQuotesData(quotes: "It is impossible to live without failing at something, unless you live so cautiously that you might as well not have lived at all - in which case, you fail by default. ― J.K. Rowling"),
        PopularQuotesData(quotes: "I have no special talent. I am only passionately curious. - Albert Einstein"),
        PopularQuotesData(quotes: "Wisely, and slow. They stumble that run fast. - William Shakespeare"),
        PopularQuotesData(quotes: "All that we are is the result of what we have thought. - Buddha"),
        PopularQuotesData(quotes: "The most courageous act is still to think for yourself. Aloud. - Coco Chane"),
        PopularQuotesData(quotes: "Stay hungry, stay foolish. - Steve Jobs"),
        PopularQuotesData(quotes: "The greatest wealth is to live content with little. - Plato"),
        PopularQuotesData(quotes: "The future belongs to those who prepare for it today. - Malcolm X"),
        PopularQuotesData(quotes: "The successful warrior is the average man, with laser-like focus. - Bruce Lee"),
        PopularQuotesData(quotes: "A great man is always willing to be little. - Ralph Waldo Emerson"),
        PopularQuotesData(quotes: "Don’t count the days, make the days count. - Muhammad Ali"),
        PopularQuotesData(quotes: "In order to be irreplaceable one must always be different. - Coco Chanel"),
        PopularQuotesData(quotes: "Be kind whenever possible. It is always possible. - Dalai Lama"),
        PopularQuotesData(quotes: "The root of suffering is attachment. - Buddha"),
        PopularQuotesData(quotes: "Well done is better than well said. - Benjamin Franklin"),
        PopularQuotesData(quotes: "It always seems impossible until it’s done. - Nelson Mandela"),
        PopularQuotesData(quotes: "Our life is frittered away by detail… simplify, simplify. - Henry David Thoreau"),
        PopularQuotesData(quotes: "Try not to become a man of success but rather to become a man of value. - Albert Einstein"),
        PopularQuotesData(quotes: "The weak can never forgive. Forgiveness is the attribute of the strong. - Mahatma Gandhi"),
        PopularQuotesData(quotes: "No matter who you are or what you look like, how you started off, or how and who you love, America is a place where you can write your own destiny. - Barack Obama"),
        PopularQuotesData(quotes: "Turn your wounds into wisdom. - Oprah Winfrey"),
        PopularQuotesData(quotes: "I don’t think of all the misery but of the beauty that still remains. - Anne Frank"),
        PopularQuotesData(quotes: "Life is a flower of which love is the honey. - Victor Hugo"),
        PopularQuotesData(quotes: "Do what you can, with what you have, where you are. - Theodore Roosevelt"),
        PopularQuotesData(quotes: "Little by little, one travels far. - J.R.R. Tolkien"),
        PopularQuotesData(quotes: "It’s not how much you have that makes people look up to you, it’s who you are. - Elvis Presley"),
        PopularQuotesData(quotes: "I fear not the man who has practiced 10,000 kicks once, but I fear the man who has practiced one kick 10,000 times. - Bruce Lee"),
        PopularQuotesData(quotes: "A man who stands for nothing will fall for anything. - Malcolm X"),
        PopularQuotesData(quotes: "You have power over your mind – not outside events. Realize this, and you will find strength. - Marcus Aurelius"),
        PopularQuotesData(quotes: "Love all, trust a few, do wrong to none. - William Shakespeare"),
        PopularQuotesData(quotes: "I have a dream that one day little black boys and girls will be holding hands with little white boys and girls. - Martin Luther King Jr"),
        PopularQuotesData(quotes: "The path to success is to take massive, determined action. - Tony Robbins"),
        PopularQuotesData(quotes: "Love the life you live. Live the life you love. - Bob Marley"),
        PopularQuotesData(quotes: "God helps those that help themselves. - Benjamin Franklin"),
        PopularQuotesData(quotes: "By failing to prepare, you are preparing to fail. - Benjamin Franklin"),
        PopularQuotesData(quotes: "I came, I saw, I conquered. - Julius Caesar"),
        PopularQuotesData(quotes: "I think, therefore I am. - René Descartes"),
        PopularQuotesData(quotes: "To be, or not to be, that is the question. - William Shakespeare"),
        PopularQuotesData(quotes: "That’s one small step for a man, one giant leap for mankind. Neil Armstrong"),
        PopularQuotesData(quotes: "The only thing that interferes with my learning is my education. - Albert Einstein"),
        PopularQuotesData(quotes: "Ask not what your country can do for you, but what you can do for your country. - John F. Kennedy"),
        PopularQuotesData(quotes: "Early to bed and early to rise makes a man healthy, wealthy, and wise. - Benjamin Franklin"),
        PopularQuotesData(quotes: "Family is the most important thing in the world. - Diana, Princess of Wales"),
        PopularQuotesData(quotes: "All I was doing was trying to get home from work. - Rosa Parks"),
        PopularQuotesData(quotes: "The journey of a thousand miles begins with one step. - Lao Tzu"),
        PopularQuotesData(quotes: "I’ve failed over and over and over again in my life and that is why I succeed. - Michael Jordan"),
        PopularQuotesData(quotes: "Float like a butterfly, sting like a bee. - Muhammad Ali"),
        PopularQuotesData(quotes: "Nonviolence is a weapon of the strong. - Mahatma Gandhi"),
        PopularQuotesData(quotes: "Not how long, but how well you have lived is the main thing. - Seneca"),
        PopularQuotesData(quotes: "It’s not whether you get knocked down, it’s whether you get up. - Vince Lombardi"),
        PopularQuotesData(quotes: "Peace begins with a smile. - Mother Teresa"),
        PopularQuotesData(quotes: "Education is the most powerful weapon which you can use to change the world. - Nelson Mandela"),
        PopularQuotesData(quotes: "Good artists copy, great artists steal. - Pablo Picasso"),
        PopularQuotesData(quotes: "Genius is one percent inspiration, ninety-nine percent perspiration. - Thomas A. Edison"),
        PopularQuotesData(quotes: "Better to die standing than to live on your knees. - Ernesto “Che” Guevara"),
        PopularQuotesData(quotes: "Keep calm and carry on. - Winston Churchill"),
        PopularQuotesData(quotes: "Genius is eternal patience. - Michelangelo"),
        PopularQuotesData(quotes: "Fear is stupid. So are regrets. - Marilyn Monroe"),
        PopularQuotesData(quotes: "Do something worth remembering. - Elvis Presley"),
        PopularQuotesData(quotes: "Elegance is refusal. - Coco Chanel"),
        PopularQuotesData(quotes: "Whatever you are, be a good one. - Abraham Lincoln"),
        PopularQuotesData(quotes: "Puns are the highest form of literature. - Alfred Hitchcock"),
        PopularQuotesData(quotes: "A boo is a lot louder than a cheer. - Lance Armstrong"),
        PopularQuotesData(quotes: "Get busy living, or get busy dying. - Stephen King"),
        PopularQuotesData(quotes: "I’m not afraid of dying, I’m afraid of not trying. - Jay-Z"),
        PopularQuotesData(quotes: "Be proud of who you are. - Eminem"),
        PopularQuotesData(quotes: "Not all those who wander are lost. - J.R.R. Tolkien"),
        PopularQuotesData(quotes: "Better to build a bridge than a wall. - Elton John"),
        PopularQuotesData(quotes: "Be the hero of your own story. - Joe Rogan"),
        PopularQuotesData(quotes: "The only failure is not to try. - George Clooney"),
        PopularQuotesData(quotes: "Nobody can hurt me without my permission. - Mahatma Gandhi"),
        PopularQuotesData(quotes: "I am the greatest, I said that even before I knew I was. - Muhammad Ali"),
        PopularQuotesData(quotes: "Winners never quit, and quitters never win. - Vince Lombardi"),
        PopularQuotesData(quotes: "Man – a being in search of meaning. - Plato"),
        PopularQuotesData(quotes: "Your past does not equal your future. - Tony Robbins"),
        PopularQuotesData(quotes: "Believe you can and you’re halfway there. - Theodore Roosevelt"),
        PopularQuotesData(quotes: "I don’t make music for eyes. I make music for ears. - Adele"),
        PopularQuotesData(quotes: "Simplicity is the ultimate sophistication. - Leonardo da Vinci"),
        PopularQuotesData(quotes: "We need fantasy to survive reality. - Lady Gaga"),
        PopularQuotesData(quotes: "It’s fun to do the impossible. - Walt Disney"),
        PopularQuotesData(quotes: "Have no fear of perfection, you’ll never reach it. - Salvador Dali"),
        PopularQuotesData(quotes: "What worries you, masters you. - John Locke"),
        PopularQuotesData(quotes: "There is nothing impossible to him who will try. - Alexander the Great"),
        PopularQuotesData(quotes: "Whatever you do, do with all your might. - Cicero"),
        PopularQuotesData(quotes: "The future starts today, not tomorrow. - Pope John Paul II"),
        PopularQuotesData(quotes: "You are what you believe yourself to be. - Paulo Coelho"),
        PopularQuotesData(quotes: "Stumbling is not falling. - Malcolm X"),
        PopularQuotesData(quotes: "The best way to predict your future is to create it. - Abraham Lincoln"),
        PopularQuotesData(quotes: "Those who dare to fail miserably can achieve greatly. - John F. Kennedy"),
        PopularQuotesData(quotes: "If not us, who? If not now, when?. - John F. Kennedy"),
        PopularQuotesData(quotes: "Starting today, we must pick ourselves up, dust ourselves off, and begin again the work of remaking America. - Barack Obama"),
        PopularQuotesData(quotes: "Ambition is a dream with a V8 engine. - Elvis Presley"),
        PopularQuotesData(quotes: "Doing the best at this moment puts you in the best place for the next moment. - Oprah Winfrey"),
        PopularQuotesData(quotes: "When our memories outweigh our dreams, it is then that we become old. - Bill Clinton"),
        PopularQuotesData(quotes: "We are all of us stars, and we deserve to twinkle. - Marilyn Monroe"),
        PopularQuotesData(quotes: "It is you, the young and fearless at heart, the most diverse and educated generation in our history, who the nation is waiting to follow. - Barack Obama"),
        PopularQuotesData(quotes: "For beautiful eyes, look for the good in others; for beautiful lips, speak only words of kindness; and for poise, walk with the knowledge that you are never alone. - Audrey Hepburn"),
        PopularQuotesData(quotes: "I am basically a feminist. I think that women can do anything they decide to do. - Grace Kelly"),
        PopularQuotesData(quotes: "Do all the good you can, for all the people you can, in all the ways you can, as long as you can. - Hillary Clinton"),
        PopularQuotesData(quotes: "Never doubt yourself. Never change who you are. Don’t care what people think and just go for it. - Britney Spears"),
        PopularQuotesData(quotes: "Power is not given to you. You have to take it. - Beyonce"),
        PopularQuotesData(quotes: "Don’t settle for what life gives you; make life better and build something. - Ashton Kutcher"),
        PopularQuotesData(quotes: "Everybody wants to be famous, but nobody wants to do the work. I live by that. You grind hard so you can play hard. At the end of the day, you put all the work in, and eventually it’ll pay off. It could be in a year, it could be in 30 years. Eventually, your hard work will pay off. - Kevin Hart"),
        PopularQuotesData(quotes: "Everything negative – pressure, challenges – is all an opportunity for me to rise. - Kobe Bryant"),
        PopularQuotesData(quotes: "I like criticism. It makes you strong. - LeBron James"),
        PopularQuotesData(quotes: "We don’t want to tell our dreams. We want to show them. - Cristiano Ronaldo"),
        PopularQuotesData(quotes: "Impossible is just a big word thrown around by small men who find it easier to live in the world they’ve been given than to explore the power they have to change it. Impossible is not a fact. It’s an opinion. Impossible is not a declaration. It’s a dare. Impossible is potential. Impossible is temporary. Impossible is nothing. - Muhammad Ali"),
        PopularQuotesData(quotes: "If people take anything from my music, it should be motivation to know that anything is possible as long as you keep working at it and don’t back down. - Eminem"),
        PopularQuotesData(quotes: "Creativity is intelligence having fun. - Albert Einstein"),
        PopularQuotesData(quotes: "I just don’t want to be hampered by my own limitations. - Barbra Streisand"),
        PopularQuotesData(quotes: "Those who say it can’t be done are usually interrupted by others doing it. - James Baldwin"),
        PopularQuotesData(quotes: "Do what you have to do, to do what you want to do. - Denzel Washington"),
        PopularQuotesData(quotes: "If I have seen further than others, it is by standing upon the shoulders of giants. - Isaac Newton"),
        PopularQuotesData(quotes: "One day, in retrospect, the years of struggle will strike you as the most beautiful. - Sigmund Freud"),
        PopularQuotesData(quotes: "Learn to value yourself, which means: to fight for your happiness. - Ayn Rand"),
        PopularQuotesData(quotes: "You’ll never find a rainbow if you’re looking down. - Charlie Chaplin"),
        PopularQuotesData(quotes: "You laugh at me because I’m different I laugh at you because you’re all the same. - Lady Gaga"),
        PopularQuotesData(quotes: "If you don’t have any shadows you’re not in the light. - Lady Gaga"),
        PopularQuotesData(quotes: "Knowing is not enough; we must apply. Willing is not enough; we must do. - Bruce Lee"),
        PopularQuotesData(quotes: "Often it isn’t the mountains ahead that wear you out, it’s the little pebble in your shoe. - Muhammad Ali"),
        PopularQuotesData(quotes: "Truth is like the sun. You can shut it out for a time, but it ain’t goin’ away. - Elvis Presley"),
        PopularQuotesData(quotes: "Too often we enjoy the comfort of opinion without the discomfort of thought. - John F. Kennedy"),
        PopularQuotesData(quotes: "It is easier to find men who will volunteer to die, than to find those who are willing to endure pain with patience. - Julius Caesar"),
        PopularQuotesData(quotes: "Life is not a problem to be solved, but a reality to be experienced. - Søren Kierkegaard"),
        PopularQuotesData(quotes: "The two most important days in your life are the day you are born and the day you find out why. - Mark Twain"),
        PopularQuotesData(quotes: "Nothing makes a woman more beautiful than the belief that she is beautiful. - Sophia Loren"),
        PopularQuotesData(quotes: "Your love makes me strong. Your hate makes me unstoppable. - Cristiano Ronaldo"),
        PopularQuotesData(quotes: "A lion doesn’t concern himself with the opinions of the sheep. - Lionel Messi"),
        PopularQuotesData(quotes: "My ruthless desire to win at all costs served me well on the bike but the level it went to, for whatever reason, is a flaw. That desire, that attitude, that arrogance. - Lance Armstrong"),
        PopularQuotesData(quotes: "I’m for truth, no matter who tells it. I’m for justice, no matter who it’s for or against. - Malcolm X"),
        PopularQuotesData(quotes: "I never thought of myself as being handsome or good-looking or whatever. I always felt like an outsider. - Elton John"),
        PopularQuotesData(quotes: "Behind every successful person lies a pack of haters. - Eminem"),
        PopularQuotesData(quotes: "Hurt me with the truth. Don’t comfort me with a lie. - Rihanna"),
        PopularQuotesData(quotes: "It’s easy to fool the eye but it’s hard to fool the heart. - Al Pacino"),
        PopularQuotesData(quotes: "Stand for something or you will fall for anything. Today’s mighty oak is yesterday’s nut that held its ground. - Rosa Parks"),
        PopularQuotesData(quotes: "The truth will set you free, but first it will piss you off. - Gloria Steinem"),
        PopularQuotesData(quotes: "Every man is guilty of all the good he did not do. - Voltaire"),
        PopularQuotesData(quotes: "In life you need either inspiration or desperation. - Tony Robbins"),
        PopularQuotesData(quotes: "Man was born free, and he is everywhere in chains. - Jean-Jacques Rousseau"),
        PopularQuotesData(quotes: "It is not in the stars to hold our destiny but in ourselves. - William Shakespeare"),
        PopularQuotesData(quotes: "Wise men talk because they have something to say; fools, because they have to say something. - Plato"),
        PopularQuotesData(quotes: "We must use time as a tool, not as a couch. - John F. Kennedy"),
        PopularQuotesData(quotes: "Simplicity is the keynote of all true elegance. - Coco Chanel"),
        PopularQuotesData(quotes: "Some day you will be old enough to start reading fairy tales again. - C.S. Lewis"),
        PopularQuotesData(quotes: "Once you’ve accepted your flaws, no one can use them against you. - George R.R. Martin"),
        PopularQuotesData(quotes: "The most important things are the hardest to say, because words diminish them. - Stephen King"),
        PopularQuotesData(quotes: "You should never take more than you give. - Elton John"),
        PopularQuotesData(quotes: "Take a long pause …breathe and know that things are happening for you not to you. - Ashton Kutcher"),
        PopularQuotesData(quotes: "It’s nice to be important, but it’s also important to be nice. Never forget that. - Sacha Baron Cohen (Borat)"),
        PopularQuotesData(quotes: "Be careful how you judge people, most of all friends. You don’t sum up a man’s life in one moment. - Al Pacino"),
        PopularQuotesData(quotes: "You never really learn much from hearing yourself speak. - George Clooney"),
        PopularQuotesData(quotes: "Doubt can motivate you, so don’t be afraid of it. Confidence and doubt are at two ends of the scale, and you need both. They balance each other out. - Barbra Streisand"),
        PopularQuotesData(quotes: "Life imposes things on you that you can’t control, but you still have the choice of how you’re going to live through this. - Céline Dion"),
        PopularQuotesData(quotes: "A wise man can play the part of a clown, but a clown can’t play the part of a wise man. - Malcolm X"),
        PopularQuotesData(quotes: "Insanity: doing the same thing over and over again and expecting different results. Albert Einstein"),
        PopularQuotesData(quotes: "A wise man can learn more from a foolish question than a fool can learn from a wise answer. - Bruce Le"),
        PopularQuotesData(quotes: "I don’t care that they stole my idea… I care that they don’t have any of their own. - Nikola Tesla"),
        PopularQuotesData(quotes: "A fool thinks himself to be wise, but a wise man knows himself to be a fool. - William Shakespeare"),
        PopularQuotesData(quotes: "Someone’s sitting in the shade today because someone planted a tree a long time ago. - Warren Buffett"),
        PopularQuotesData(quotes: "Truth is ever to be found in simplicity, and not in the multiplicity and confusion of things. - Isaac Newton"),
        PopularQuotesData(quotes: "To know that we know what we know, and to know that we do not know what we do not know, that is true knowledge. - Nicolaus Copernicus"),
        PopularQuotesData(quotes: "There is nothing so useless as doing efficiently that which should not be done at all. - Peter Drucker"),
        PopularQuotesData(quotes: "People are more impressed by the power of our example rather than the example of our power. - Bill Clinton"),
        PopularQuotesData(quotes: "Honesty is the first chapter in the book of wisdom. - Thomas Jefferson"),
        PopularQuotesData(quotes: "The sign of intelligence is that you are constantly wondering. Idiots are always dead sure about every damn thing they are doing in their life. ― Sadhgaru"),
        PopularQuotesData(quotes: "If you ask a tree how he feels to know that he's spreading his fragrance and making people happy, I don't think a tree looks at it that way. I am just like that, and it is just my nature to be like this. ― Sadhguru"),
        PopularQuotesData(quotes: "Doubt is not a pleasant condition, but certainty is absurd. - Voltaire"),
        PopularQuotesData(quotes: "Science is organized knowledge. Wisdom is organized life. - Immanuel Kant"),
        PopularQuotesData(quotes: "Do not pray for easy lives, pray to be stronger men. - John F. Kennedy"),
        PopularQuotesData(quotes: "Life is never easy. There is work to be done and obligations to be met – obligations to truth, to justice, and to liberty. - John F. Kennedy"),
        PopularQuotesData(quotes: "If I’d observed all the rules, I’d never got anywhere. - Marilyn Monroe"),
        PopularQuotesData(quotes: "Two roads diverged in a wood, and I took the one less traveled by, and that has made all the difference. - Robert Frost"),
        PopularQuotesData(quotes: "When you are happy you can forgive a great deal. - Diana (Princess of Wales)"),
        PopularQuotesData(quotes: "Mistakes are the price of an interesting life. - Sophia Loren"),
        PopularQuotesData(quotes: "My life didn’t please me, so I created my life. - Coco Chanel"),
        PopularQuotesData(quotes: "Elegance is when the inside is as beautiful as the outside. - Coco Chane"),
        PopularQuotesData(quotes: "The road to success is not easy to navigate, but with hard work, drive and passion, it’s possible to achieve the American dream. - Tommy Hilfige"),
        PopularQuotesData(quotes: "Live for each second without hesitation. - Elton John"),
        PopularQuotesData(quotes: "What is drama, after all, but life with the dull bits cut out. - Alfred Hitchcock"),
        PopularQuotesData(quotes: "Be cool to people. Be nice to as many people as you can. Smile to as many people as you can, and have them smile back at you. - Joe Rogan"),
        PopularQuotesData(quotes: "I’m an all-or-nothing kind of person, and when I become interested in something, I give it my all. - Tom Cruis"),
        PopularQuotesData(quotes: ""),
        PopularQuotesData(quotes: "There is no happiness. There is only concentration. - Al Pacino"),
        PopularQuotesData(quotes: "It’s not about an opening weekend. It’s about a career, building a set of films you’re proud of. Period. - George Clooney"),
        PopularQuotesData(quotes: "Life is like riding a bicycle. To keep your balance, you must keep moving. - Albert Einstein"),
        PopularQuotesData(quotes: "The best answer to anger is silence. - Marcus Aurelius"),
        PopularQuotesData(quotes: "To live happily is an inward power of the soul. - Marcus Aurelius "),
        PopularQuotesData(quotes: "Confidence is contagious. So is a lack of confidence. - Vince Lombardi"),
        PopularQuotesData(quotes: "The thing to do is enjoy the ride while you’re on it. - Johnny Depp"),
        PopularQuotesData(quotes: "Too many people are hungry not because there is dearth of food. It is because there is dearth of love and care in human hearts. ― Sadhguru"),
        PopularQuotesData(quotes: "The most beautiful moments in life are moments when you are expressing your joy, not when you are seeking it. - Sadguru"),
        PopularQuotesData(quotes: "When pain, misery, or anger happen, it is time to look within you, not around you. ― Sadhguru"),
        PopularQuotesData(quotes: "The formula of happiness and success is just being actually yourself, in the most vivid possible way you can. - Meryl Streep"),
        PopularQuotesData(quotes: "Happiness lies in the joy of achievement and the thrill of creative effort. - Franklin D. Roosevelt"),
        PopularQuotesData(quotes: "Good friends, good books, and a sleepy conscience: this is the ideal life. - Mark Twain"),
        PopularQuotesData(quotes: "A man who dares to waste one hour of time has not discovered the value of life. - Charles Darwin"),
        PopularQuotesData(quotes: "God gave us the gift of life; it is up to us to give ourselves the gift of living well. - Voltaire"),
        PopularQuotesData(quotes: "You can discover more about a person in an hour of play than in a year of conversation. - Plato"),
        PopularQuotesData(quotes: "Life is a succession of lessons which must be lived to be understood. - Helen Keller"),
        PopularQuotesData(quotes: "If you don’t live your life, who the f*ck will?. - Rihanna"),
        PopularQuotesData(quotes: "You cannot find peace by avoiding life. - Virginia Woolfe"),
        PopularQuotesData(quotes: "We are what we repeatedly do; excellence, then, is not an act but a habit. - Aristotle"),
        PopularQuotesData(quotes: "If you’re walking down the right path and you’re willing to keep walking, eventually you’ll make progress. - Barack Obama"),
        PopularQuotesData(quotes: "Every accomplishment starts with the decision to try. - John F. Kennedy"),
        PopularQuotesData(quotes: "Efforts and courage are not enough without purpose and direction. - John F. Kennedy"),
        PopularQuotesData(quotes: "A wise girl knows her limits, a smart girl knows that she has none. - Marilyn Monroe"),
        PopularQuotesData(quotes: "Success isn’t about how much money you make. It’s about the difference you make in people’s lives. - Michelle Obama"),
        PopularQuotesData(quotes: "Don’t pay any attention to what they write about you. Just measure it in inches. - Andy Warhol"),
        PopularQuotesData(quotes: "The fear is simply because you are not living with life, You are living in your mind. ― Sadhguru"),
        PopularQuotesData(quotes: "Love is your quality. Love is not what you do. Love is what you are.- Sadhguru"),
        PopularQuotesData(quotes: "To be successful you have to be selfish, or else you never achieve. And once you get to your highest level, then you have to be unselfish. Stay reachable. Stay in touch. Don’t isolate. - Michael Jordan"),
        PopularQuotesData(quotes: "That was my way of getting through difficult times of low confidence – hard work. - David Beckham"),
        PopularQuotesData(quotes: "Success is no accident. It is hard work, perseverance, learning, studying, sacrifice and most of all, love of what you are doing or learning to do. - Pelé"),
        PopularQuotesData(quotes: "If I make a fool of myself, who cares? I’m not frightened by anyone’s perception of me. - Angelina Jolie"),
        PopularQuotesData(quotes: "Success isn’t always about greatness. It’s about consistency. Consistent hard work leads to success. Greatness will come. - Dwayne Johnson (The Rock"),
        PopularQuotesData(quotes: "The finest steel has to go through the hottest fire. - Richard M. Nixon"),
        PopularQuotesData(quotes: "My religion is very simple. My religion is kindness. - Nelson Mandela"),
        PopularQuotesData(quotes: "And know that I am with you always; yes, to the end of time. - Jesus Chris"),
        PopularQuotesData(quotes: "We are twice armed if we fight with faith. - Plato"),
        PopularQuotesData(quotes: "A leader is a dealer in hope. - Napoleon Bonaparte"),
        PopularQuotesData(quotes: "We can do anything we want to if we stick to it long enough. - Helen Kelle"),
        PopularQuotesData(quotes: "If you don’t like something, change it. If you can’t change it, change your attitude. - Maya Angelou"),
        PopularQuotesData(quotes: "If you want to make enemies, try to change something. - Woodrow Wilson"),
        PopularQuotesData(quotes: "One child, one teacher, one book, one pen can change the world. - Malala Yousafzai"),
        PopularQuotesData(quotes: "The mind, once stretched by a new idea, never returns to its original dimensions. - Ralph Waldo Emerson"),
        PopularQuotesData(quotes: "There is no greater education than one that is self-driven. - Neil deGrasse Tyson"),
        PopularQuotesData(quotes: "You should learn from your competitor, but never copy. Copy and you die. - Jack Ma"),
        PopularQuotesData(quotes: "Krishna says in the Gita, “The worst crime in the world is indecision. ― Sadhguru"),
        PopularQuotesData(quotes: "I have lived my life according to this principle: If I’m afraid of it, then I must do it. - Erica Jong"),
        PopularQuotesData(quotes: "A hero is no braver than an ordinary man, but he is brave five minutes longer. - Ralph Waldo Emerson"),
        PopularQuotesData(quotes: "There are times when explanations, no matter how reasonable, just don’t seem to help. - Fred Rogers"),
        PopularQuotesData(quotes: "You are strong. You are beautiful. You are resilient. You are loved. You are capable. You are not weak. You are not defected. You are not weird. You are not a lost cause. You are not different. - The Anxiety Man"),
        PopularQuotesData(quotes: "It is easy to be heavy: hard to be light. - G.K. Chesterton"),
        PopularQuotesData(quotes: "No storm, not even the one in your life, can last forever. The storm is just passing over. - Iyanla Vanzant"),
        PopularQuotesData(quotes: "The shadows are as important as the light. - Charlotte Brontë"),
        PopularQuotesData(quotes: "Respect yourself and others will respect you. - Confucius"),
        PopularQuotesData(quotes: "I think the reward for conformity is that everyone likes you except yourself. - Rita Mae Brown"),
        PopularQuotesData(quotes: "Always be yourself, express yourself, have faith in yourself, do not go out and look for a successful personality and duplicate it. - Bruce Lee"),
        PopularQuotesData(quotes: "Be tolerant with others and strict with yourself. - Marcus Aurelius"),
        PopularQuotesData(quotes: "The rich invest in time, the poor invest in money. - Warren Buffett"),
        PopularQuotesData(quotes: "If you make meaning, you’ll make money. - Guy Kawasaki "),
        PopularQuotesData(quotes: "Trade money for time, not time for money. You’re going to run out of time first. - Naval Ravikan"),
        PopularQuotesData(quotes: "My favorite things in life don’t cost any money. It’s really clear that the most precious resource we all have is time. - Steve Jobs"),
        PopularQuotesData(quotes: "t is health that is real wealth and not pieces of gold and silver. - Mahatma Gandhi"),
        PopularQuotesData(quotes: "He who has health has hope; and he who has hope has everything. - Arabian proverb"),
        PopularQuotesData(quotes: "You don’t choose your family. They are god’s gift to you, as you are to them. - Desmond Tutu"),
        PopularQuotesData(quotes: "The more you’re loving and understanding, the more your kids will sing. - Maxime Lagacé"),
        PopularQuotesData(quotes: "A man can’t make a place for himself in the sun if he keeps taking refuge under the family tree. - Helen Keller"),
        PopularQuotesData(quotes: "The greatest gifts you can give your children are the roots of responsibility and the wings of independence. - Denis Waitle"),
        PopularQuotesData(quotes: "We must fall in love with ourselves. I don’t like myself. I’m crazy about myself. - Mae Wes"),
        PopularQuotesData(quotes: "Because one believes in oneself, one doesn’t try to convince others. Because one is content with oneself, one doesn’t need others’ approval. Because one accepts oneself, the whole world accepts him or her. - Lao Tzu"),
        PopularQuotesData(quotes: "You start to live the moment you stop competing with others. - Maxime Lagacé"),
        PopularQuotesData(quotes: "Just be, and enjoy being. - Eckhart Tolle"),
        PopularQuotesData(quotes: "The moment you accept yourself, you become beautiful. - Osho"),
        PopularQuotesData(quotes: "Too many prefer gentle lies to hard truths. - Shane Parrish"),
        PopularQuotesData(quotes: "The ideals which have always shone before me and filled me with joy are goodness, beauty, and truth. - Albert Einstein "),
        PopularQuotesData(quotes: "Sometimes people don’t want to hear the truth because they don’t want their illusions destroyed. - Friedrich Nietzsche"),
        PopularQuotesData(quotes: "Know that you don’t know. That is superior. - Lao Tzu"),
        PopularQuotesData(quotes: "Knowledge will give you power, but character respect. - Bruce Lee"),
        PopularQuotesData(quotes: "The dumbest people I know are those who know it all. - Malcolm Forbe"),
        PopularQuotesData(quotes: "Wisdom is not a product of schooling but of the lifelong attempt to acquire it. - Albert Einstein"),
        PopularQuotesData(quotes: "Knowledge is a process of piling up facts; wisdom lies in their simplification. - Martin Luther King Jr "),
        PopularQuotesData(quotes: "There is no fear for one whose mind is not filled with desires. - Buddha"),
        PopularQuotesData(quotes: "A man is not called wise because he talks and talks again; but if he is peaceful, loving and fearless then he is in truth called wise. - Buddha"),
        PopularQuotesData(quotes: "Gratitude turns what we have into enough. - Aesop"),
        PopularQuotesData(quotes: "This is a wonderful day. I’ve never seen this one before. - Maya Angelou"),
        PopularQuotesData(quotes: "An early-morning walk is a blessing for the whole day. - Henry David Thoreau"),
        PopularQuotesData(quotes: "A relationship where you can be weird together is your best choice. - Paulo Coelho"),
        PopularQuotesData(quotes: "Life appears to me too short to be spent in nursing animosity or registering wrongs. - Charlotte Brontë"),
        PopularQuotesData(quotes: "Treat everyone as if they were a guest in your own house, because in reality, they are a guest in your own world. - B. D. Schiers"),
        PopularQuotesData(quotes: "There’s only one thing more precious than our time and that’s who we spend it on. - Leo Christopher"),
        PopularQuotesData(quotes: "A calm and modest life brings more happiness than the pursuit of success combined with constant restlessness. - Albert Einstein"),
        PopularQuotesData(quotes: "Stress and confusion come from being busy. Peace and clarity come from slowing down and stilling your waters. - Maxime Lagacé"),
        PopularQuotesData(quotes: "In a world deluged by irrelevant information, clarity is power. - Yuval Noah Harar"),
        PopularQuotesData(quotes: "Success demands singleness of purpose. - Vince Lombardi"),
        PopularQuotesData(quotes: "Focus does not mean saying yes, it means saying no. - Steve Jobs"),
        PopularQuotesData(quotes: "Only through focus can you do world-class things, no matter how capable you are. - Bill Gates"),
        PopularQuotesData(quotes: "It is those who concentrate on but one thing at a time who advance in this world. - Og Mandino"),
        PopularQuotesData(quotes: "Effectiveness begins with elimination. Choose your ignorances as carefully as your interests. - The Stoic Emperor"),
        PopularQuotesData(quotes: "Too much sugar leads to a heavy body, and too many distractions lead to a heavy mind. - Naval Ravikant"),
        PopularQuotesData(quotes: "I’ll live the focused life, because it’s the best kind there is. - Winifred Gallaghe"),
        PopularQuotesData(quotes: "If I had an hour to solve a problem, I’d spend 55 minutes thinking about the problem and 5 minutes thinking about solutions. - Albert Einstein"),
        PopularQuotesData(quotes: "Where you are headed is more important than how fast you are going. Rather than always focusing on what’s urgent, learn to focus on what is really important. - Stephen R. Covey"),
        PopularQuotesData(quotes: "You will never reach your destination if you stop and throw stones at every dog that barks. - Winston Churchill"),
        PopularQuotesData(quotes: "Our life always expresses the result of our dominant thoughts. - Søren Kierkegaard"),
        PopularQuotesData(quotes: "It is good to have a goal, but bad to let your goal have you. Focus is good, but focus that is too narrow becomes blindness. - The Stoic Emperor"),
        PopularQuotesData(quotes: "Most of what we say and do is not essential. If you can eliminate it, you’ll have more time, and more tranquillity. Ask yourself at every moment, “Is this necessary?” - Marcus Aurelius"),
        PopularQuotesData(quotes: "You’re tired and scared. Happens to everyone, okay? Just don’t let your feet stop. - Haruki Murakami"),
        PopularQuotesData(quotes: "Soon, when all is well, you’re going to look back on this period of your life and be so glad that you never gave up. - Brittany Burgunder"),
        PopularQuotesData(quotes: "Trying and struggling looks like incompetence right up until the moment it looks like success. - Shane Parrish"),
        PopularQuotesData(quotes: "No matter what, just keep going. - Maxime Lagacé"),
        PopularQuotesData(quotes: "There are far, far better things ahead than any we leave behind. - C.S. Lewis"),
        PopularQuotesData(quotes: "But if a thing is humanly possible, consider it to be within your reach. - Marcus Aurelius"),
        PopularQuotesData(quotes: "Don’t worry about all of the steps. Begin. - Bob Goff"),
        PopularQuotesData(quotes: "The path through trouble is always made a step at a time, a breath at a time, a day at a time. - Jack Kornfield"),
        PopularQuotesData(quotes: "It’s okay to feel lost, it’s okay to feel pain, it’s okay to feel hopeless. What’s not okay is thinking life will be easy. Stay strong my friend. - Maxime Lagacé"),
        PopularQuotesData(quotes: "I will keep preaching this to myself and others: there are no problems, only projects. - David Allen"),
        PopularQuotesData(quotes: "Not seeing results? Feel like giving up? Consider this: the last thing to grow on a fruit tree… is the fruit. Doing amazing sh*t takes time. You want that fruit you gotta stay after it. - Tom Bilyeu"),
        PopularQuotesData(quotes: "Get a move on…Don’t worry whether anyone will give you credit for it…Be satisfied with even the smallest progress, and treat the outcome of it all as unimportant. - Marcus Aurelius"),
        PopularQuotesData(quotes: "Pick your one overwhelming desire. It’s okay to suffer over that one. - Naval Ravikant"),
        PopularQuotesData(quotes: "Once you choose hope, anything’s possible. - Christopher Reeve"),
        PopularQuotesData(quotes: "We must accept finite disappointment, but never lose infinite hope. - Martin Luther King Jr"),
        PopularQuotesData(quotes: "Everything that is done in this world is done by hope. - Martin Luther"),
        PopularQuotesData(quotes: "May your choices reflect your hopes, not your fears. - Nelson Mandela"),
        PopularQuotesData(quotes: "Hope is being able to see that there is light despite all of the darkness. - Desmond Tutu"),
        PopularQuotesData(quotes: "Patience is bitter, but its fruit is sweet. - Aristotle "),
        PopularQuotesData(quotes: "Sit with the pain until it passes, and you will be calmer for the next one. - Naval Ravikant"),
        PopularQuotesData(quotes: "Without pain, without sacrifice, we would have nothing. - Fight Club"),
        PopularQuotesData(quotes: "Let go of the past. - Robert Greene"),
        PopularQuotesData(quotes: "Adversity is the first path to truth. - Lord Byron"),
        PopularQuotesData(quotes: "Great things never came from comfort zones. - Neil Strauss"),
        PopularQuotesData(quotes: "Although the world is full of suffering, it is full also of the overcoming of it. - Helen Keller"),
        PopularQuotesData(quotes: "True self-discovery begins where your comfort zone ends. - Adam Braun"),
        PopularQuotesData(quotes: "One word frees us of all the weight and pain of life: that word is love. - Sophocles"),
        PopularQuotesData(quotes: "New beginnings are often disguised as painful endings. - Lao Tzu"),
        PopularQuotesData(quotes: "If you are distressed by anything external, the pain is not due to the thing itself, but to your estimate of it; and this you have the power to revoke at any moment. - Marcus Aurelius"),
        PopularQuotesData(quotes: "You never know how strong you are until being strong is your only choice. - Bob Marley"),
        PopularQuotesData(quotes: "Every pain is a gift. Every pain is an opportunity. - Maxime Lagacé"),
        PopularQuotesData(quotes: "What hurts us is what heals us. - Paulo Coelho"),
        PopularQuotesData(quotes: "Out of suffering have emerged the strongest souls; the most massive characters are seared with scars. - Kahlil Gibran"),
        PopularQuotesData(quotes: "People go through so much pain trying to avoid pain. - Neil Strauss"),
        PopularQuotesData(quotes: "Pain makes me grow. Growing is what I want. Therefore, for me pain is pleasure. - Arnold Schwarzenegger"),
        PopularQuotesData(quotes: "It is when I struggle that I strengthen. It is when challenged to my core that I learn the depth of who I am. - Steve Maraboli"),
        PopularQuotesData(quotes: "Behind every beautiful thing, there’s been some kind of pain. - Bob Dylan"),
        PopularQuotesData(quotes: "I’ve decided to make myself strong. As far as I can tell, that’s all I can do. - Haruki Murakami"),
        PopularQuotesData(quotes: "No matter what they say, no matter what they think, do the right thing. - Maxime Lagacé"),
        PopularQuotesData(quotes: "Fire is the test of gold; adversity, of strong men. - Seneca"),
        PopularQuotesData(quotes: "The art of life is not controlling what happens to us, but using what happens to us. - Gloria Steinem"),
        PopularQuotesData(quotes: "Don’t go to the doctor with every distemper, nor to the lawyer with every quarrel, nor to the pot for every thirst. - Benjamin Franklin"),
        PopularQuotesData(quotes: "So other people hurt me? That’s their problem. Their character and actions are not mine. - Marcus Aurelius"),
        PopularQuotesData(quotes: "Either you reach a higher point today, or you exercise your strength in order to be able to climb higher tomorrow. - Friedrich Nietzsche"),
        PopularQuotesData(quotes: "To try to avoid pain is to give too many f*cks about pain. In contrast, if you’re able to not give a f*ck about pain, you become unstoppable. - Mark Manson"),
        PopularQuotesData(quotes: "Mankind has never achieved greatness but through suffering. - Robert de Lamennais"),
        PopularQuotesData(quotes: "If you only walk on sunny days you’ll never reach your destination. - Paulo Coelho"),
        PopularQuotesData(quotes: "There’s no hope if people expect life to be easy. There’s a future if people believe they must be strong. - Maxime Lagacé"),
        PopularQuotesData(quotes: "After crosses and losses men grow humbler and wiser. - Benjamin Franklin"),
        PopularQuotesData(quotes: "If it scares me, there’s magic on the other side. - Kamal Ravikant"),
        PopularQuotesData(quotes: "You cannot experience the fullness of your life when you live to avoid hurt. - Iyanla Vanzant"),
        
   ]
    
    
    

    
   static func getPopularQuotes(from Index: Int ) -> String {
     
        return PopularQuotesModel.quotesList[Index].quotes
   
    }
    
}

    
    
    







